version: '3.8'

services:
  backend:
    build: .
    container_name: 'backend'
    restart: on-failure
    depends_on: 
      rabbitmq:
        condition: service_healthy
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    